### ISSUE TITLE
How to replace https://github.com/davibennun/laravel-push-notification

### ISSUE THREAD

**Issue by sarveshamrit** [khrizt/PushNotiphications#3]
Can u teach how to replace https://github.com/davibennun/laravel-push-notification/ with yours?

**Comment by khrizt** [comment]
Hi sarveshamrit,

Without looking at the actual code it's gonna be difficult but the implementation is not that different, check out the [README](https://github.com/khrizt/PushNotiphications/blob/master/README.md) file and replace their classes with mine, for example `DeviceCollection` for `Collection`.

I recommend you do an abstract layer to interact with this library, or any other, so when switching from one library to another you only need to change this layer.

If you need more help in something more concrete tell me, but without seeing the actual implementation I can't help you more.

**Comment by sarveshamrit** [comment]
Sir if u could pass me your email id i can pay you to implement your to to my existing system plz

**Comment by khrizt** [comment]
Sorry I don't do freelancing work. But I'll try to help if you have any doubts when migrating

**Comment by sarveshamrit** [comment]
but which should i replace your with? the notification pusher https://github.com/Ph3nol/NotificationPusher or https://github.com/davibennun/laravel-push-notification/

**Comment by khrizt** [comment]
In the first comment you said you wanted to replace `lavarel-push-notification` with this package, now you want to do it backwards. I don't know what is the difficulty you have with this library but last I checked, it worked correctly.

That said, choose whichever library suits you best I'm sure all of them work well. I've tried Ph3nol's one in the past and it worked very well.

**Comment by sarveshamrit** [comment]
sir if u could give your mail id i will send me server details to look after if u don't mind

In the current structure of application, its using lavarel-push-notification which uses ph3nol and that works with zend apns so i am confused what to replace with that

**Comment by khrizt** [comment]
If you have a problem with `lavarel-push-notification` you should open an issue there. This library is a laravel implementation of the ph3nol's library, so if you are really sure that the problem is in the ph3nol library you should open an issue in the ph3nol's issue page.

I'm sorry I can't help you more, but as I said previously I don't do freelancing work. But if you really want to switch to this library you could check the [Push command](https://github.com/khrizt/PushNotiphications/blob/master/src/Khrizt/PushNotiphications/Console/Commands/PushCommand.php) to see an example on how to use this library.
